#version : '3.8'
#services:
#  web:
#    image: nginx:latest
#    ports:
#      - "8888:80"
#  db:
#    image: postgres:15-alpine
#    ports:
#      - "${POSTGRES_PORT}:5432"  # 호스트:컨테이너 포트 매핑
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data


  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: