#version : '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vue-frontend-build
    command: echo "Frontend built."
    volumes:
        - ./frontend/dist:/app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    depends_on:
      - backend
    networks:
      - appnet

  db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
