spring:
  application:
    name: lordlog
  datasource:
    url: jdbc:postgresql://db:5432/loh_db
    username: lordlogs
    password: 9539a233-bc2a-4897-af0c-ef484d6c404e
    driver-class-name: org.postgresql.Driver
  #메일 설정
  mail:
    host: smtp.gmail.com
    port: 587 #TLS
    username: rosharonl22@gmail.com
    password: egiq xyny pgfk lpxv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.loharchive.lordlog: DEBUG
    org.mybatis: DEBUG

mail:
  admin-address: contact@lordarchieve.com