name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle with dependency graph
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      with: 
        dependency-graph: generate-and-submit

    - name: Build with Gradle Wrapper except Test
      run: ./gradlew build -x test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Get current IP and update security group
      run: |
        CURRENT_IP=$(curl -s https://api.ipify.org)
        
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${CURRENT_IP}/32 \
          --description "GitHub Actions temporary access"

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
           echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/app/.env
          
            cd /home/ubuntu/app
          
            if [ ! -d "backend/.git" ]; then
              git clone https://github.com/Sharon-l-Lee/lohAPI.git backend
            else
              cd backend && git pull origin main && cd ..
            fi
          
            docker compose build backend
            docker compose restart backend

    - name: Remove IP from security group
      if: always()
      run: |
        CURRENT_IP=$(curl -s https://api.ipify.org)
        
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${CURRENT_IP}/32
