name: SSH Key Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      - name: Add private key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes ubuntu@${{ secrets.SSH_HOST }} echo "✅ SSH 연결 성공!"
